### ISSUE TITLE
improve barel path

### ISSUE THREAD

**Issue by alevin** [gwhs/FalconRecharged2021#10]
barrel run from  03.01  ( ~16 sec , one marker touched ) 
[code](https://github.com/gwhs/FalconRecharged2021/releases/tag/Ver.2021.03.01)

[image](https://photos.app.goo.gl/S59mtuCMZLBNJyc16)

trajectory:
```java
     public static double[][] barrel = {
        {30,90},
        {60,90},
        {120,90},
        {150,90},
        {180,110},
        {180,140},
        {150,150},
        {110,140},
        {110,90},
        {160,90},
        {200,105},
        {225,110},
        {260,90},
        {270,60},
        {270,40},
        {240,30},
        {190,40},
        {190,80},
        {230,120},
        {250,140},
        {290,150},
        {310,130},
        {310,90},
        {210,90},
        {120,85},
        {80,85},
        {25,85},
        };
```
![image](https://user-images.githubusercontent.com/1231948/109732279-c0bc0300-7b71-11eb-8748-518591b8d67b.png)

review actual run ( in video ) and improve the trajectory

**Comment by alevin** [comment]
path from Monday ( 02.08 ) was not right:


```java
     public static double[][] barrel = {
        {30,90},
        {60,90},
        {120,90},
        {150,90},
        {180,110},
        {180,140},
        {150,150},
        {110,140},
        {110,80},
        {225,110},
        {260,90},
        {270,60},
        {270,30},
        {190,30},
        {190,80},
        {230,120},
        {250,140},
        {320,150},
        {320,80},
        {80,80},
        {25,80},
                };

```
![barrel](https://user-images.githubusercontent.com/1231948/110709076-86291a80-81b0-11eb-8f28-2527760e281c.png)


[video](https://photos.app.goo.gl/P3r66N8XcCcTMbpLA)

**Comment by alevin** [comment]
barrel change is reflected in [](https://github.com/gwhs/FalconRecharged2021_trajectories/commit/be15797aad2fea186a57f5566e7984b17ee8e251)
[](https://github.com/gwhs/FalconRecharged2021_trajectories/raw/main/barrel/barrel.png)

**Comment by alevin** [comment]
we had successful run with time 16:00 s - not bad , but increased speed and acceleration resulted in broken  trajectory.
I've created "AutoNav_fork" fork  at b4b24f3  ( successful run ) , before we tried to increase velocity and acceleration.
I suggest to:
1. repeat the same run
2. change trajectory ( details bellow ) 
3. repeat run
4. if successful - increase speed to 5 m/s
5. if successful add .5 to linear acceleration.

about alternative trajectory - played a bit with pathweaver  and suspect that the path we were running:
![Screenshot at 2021-03-21 13-12-09](https://user-images.githubusercontent.com/1231948/112052608-8ca08600-8b10-11eb-88cd-5144303242a2.png)

should be changed to something like 
![Screenshot at 2021-03-21 13-25-37](https://user-images.githubusercontent.com/1231948/112052787-bfe31500-8b10-11eb-88f9-893168dc7b8d.png)

( move from markers on the way back) 
it is not clear how to model such splines properly, tried few models in python and clamped cubic spline seems to be close enough 

look at code in  https://github.com/gwhs/FalconRecharged2021_trajectories/tree/main/python
to use it copy one of barrel*csv file to new "barrel" file and run  
```
plot_path.py -i <name_of_file>
```
[suggested route:](https://github.com/gwhs/FalconRecharged2021_trajectories/blob/main/python/barrel_test.png?raw=true)

```java
	{30,90},	// 1
	{60,90},	// 2
	{120,90},	// 3
	{150,90},	// 4
	{180,110},	// 5
	{180,140},	// 6
	{150,150},	// 7
	{110,140},	// 8
	{120,82},	// 9
	{205,110},	// 10
	{260,90},	// 11
	{270,30},	// 12
	{215,22},	// 13
	{192,40},	// 14
	{192,80},	// 15
	{230,120},	// 16
	{295,150},	// 17
	{280,75},	// 18
	{45,70},	// 19

```

**Comment by jhajel** [comment]
Can this issue be closed?  Are we optimizing this any more?

**Comment by alevin** [comment]
Closing the issue , we've got successful run which should be acceptable for submission.
we'll re-open  ( or open new case ) if we'll have time to improve after completion of other challenges.

great  job , @anton-levin ,  @leinouye , @zhxu033  !
