### ISSUE TITLE
Skills Challenge Tracker

### ISSUE THREAD

**Issue by jhajel** [gwhs/FalconRecharged2021#11]
I've created a skills challenge tracker spreadsheet.  Please fill out as we get going.  We will need this when we submit our scores and videos.

[https://docs.google.com/spreadsheets/d/1hon5MRLS47aLoeBlcUAX2H4hQqfORnTm2V3UvvDnpOE/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1hon5MRLS47aLoeBlcUAX2H4hQqfORnTm2V3UvvDnpOE/edit?usp=sharing)

**Comment by alevin** [comment]
Skills Challenge |% complete |Daphne Potential |Link to Video|Score/time |Notes
-----------------|-----------|-----------------|-------------|-----------|-----
Galactic Search A|50|Fair      | | |Nice to get full swerve-drive auto working
Galactic Search B|50|Fair      | | |Nice to get full swerve-drive auto working
AutoNav - Barrel Racing|90|Fair| | |			
AutoNav - Slalom|90|Fair| | |			
AutoNav - Bounce|90|Fair| | |		
Hyperdrive - Barrel Racing|95|Excellent| | |Swerve-drive should excel here
Hyperdrive - Slalom|95|Excellent| | |			
Hyperdrive - Bounce|95|Excellent| | |			
Hyperdrive - Lightspeed Circuit|95|Excellent| | |Saw a team with a 22 second time
Interstellar Accuracy Challenge|50|Poor| | |"Can only shoot from Green zone, maybe Yellow.  Best score could be 18 (6 inner port). No need for intake here either (always intake from re-introduction zone)"
Power Port Challenge|50|Good| | |"Need to fix auto-shoot command, 5 cycles would be ideal in one minute.  May need 2 human players, Great score is 45. Maybe work without intake"

**Comment by alevin** [comment]
current state:
Skills Challenge | time | penalty (markers hit) |Notes
-----|-----|-----|-----
Hyperdrive - Slalom|  12 | 1 |
Hyperdrive - Barrel Racing| 16 | 1 |
Hyperdrive - Bounce | | |

**Comment by jhajel** [comment]
Why are we hitting markers?  Is the robot too big or does Anton need more practice?  By the way, these times look great.

**Comment by alevin** [comment]
corrected my comment it is autonav

**Comment by jhajel** [comment]
Ok, I found some times to shoot for from a good team from Virginia. https://www.youtube.com/user/TripleHelix2363/videos

Autonav - Slalom: 9.55 seconds
Autonav - Bounce: 9.98
Autonav - Barrel: no time yet
Hyperdrive - Slalom: 9.78
Hyperdrive - Bounce: 11.25
Hyperdrive - Barrel: 12.08
Hyperdrive - Lightspeed: 22.55

No Galactic Search so I wonder if they are skipping it.

**Comment by alevin** [comment]
current state:
Skills Challenge | time | penalty (markers hit) |Notes
-----|-----|-----|-----
Autonav - Slalom|  12.4 | 0 | [video](https://photos.app.goo.gl/t6fMaEezwHBJwi7J7)
Autonav - Barrel Racing| 15.8 | 0 | [video](https://photos.app.goo.gl/qCYCEZAGU8GjHkKp9)

**Comment by alevin** [comment]
current state:
Skills Challenge | time | penalty (markers hit) |Notes
-----|-----|-----|-----
Autonav - Slalom|  09.71 | 0 | [video](https://photos.app.goo.gl/GXKwWM4igZ7KB699A)
Autonav - Barrel Racing| 14.35 | 0 | [video](https://photos.app.goo.gl/GXKwWM4igZ7KB699A)

**Comment by jhajel** [comment]
That's fantastic!  I think we can speed up Barrel Racing.  Now we need to get Bounce to work and we will have a good AutoNav score.

**Comment by jhajel** [comment]
Here is a thought.  During slalom can we start with the robot on an angle so it is facing the direction of the first waypoint.  It won't need to take that hard turn in the beginning.  I bet we could shave .2 seconds or more.  The question is if the robot zeroes the navX when we enable auton.  I think the first step would to try the angled start method in Tele-op (after zeroing the navX straight ahead) to see if it actually does cut time.  If it does, we can alter the code to keep from zeroing the navX on enable.

**Comment by alevin** [comment]
current state:
Skills Challenge | time | penalty (markers hit) |Notes
-----|-----|-----|-----
Bounce |  19.7 | 0 | [video](https://photos.app.goo.gl/Gu2JtScnMmsNc1xw6) 


@leinouye ,  @anton-levin

**Comment by jhajel** [comment]
Wow!  This is fantastic.  Nice job.  I can't wait to see the code.

**Comment by alevin** [comment]
current state:
Skills Challenge | time | penalty (markers hit) |Notes
-----|-----|-----|-----
Autonav Bounce |  16.00s | 0 | [video](https://photos.app.goo.gl/BQ4NPogJMbhmvjy29) 
HyperDrive Barrel |  11.24s | 0 | [video](https://photos.app.goo.gl/WAGM9YF8W7XxTvJ47) 


@leinouye , @zhxu033  ,  @anton-levin

**Comment by jhajel** [comment]
These are fantastic!  Well done.  I update the spreadsheet with the times.  I didn't update the videos yet as we may get better times.

https://docs.google.com/spreadsheets/d/1hon5MRLS47aLoeBlcUAX2H4hQqfORnTm2V3UvvDnpOE/edit#gid=0

What is the next step?

**Comment by jhajel** [comment]
We will need separate videos for each of the Galactic Search paths.

![image](https://user-images.githubusercontent.com/19674978/113451907-cfd3e200-93b7-11eb-9e4d-0e773bdab26d.png)

**Comment by jhajel** [comment]
Also, check the link on the video for the Galactic Search.  It seems to come back to this page.

**Comment by alevin** [comment]
Videos for galactic search Red an Blue Path A and Path B , AutoNav barrel, bounce, slalom and for HyperDrive barrel are uploaded to Google drive - folder "Infinite Recharge at Home/Video for submission"

**Comment by jhajel** [comment]
The video in the folder for HD_Barrel is for 11.31 secs, but I think our best time is 11.24.  Is that the case?

**Comment by alevin** [comment]
Skills Challenge | time | penalty (markers hit) |Notes
-----|-----|-----|-----
HyperDrive Bounce |  10.21s | 0 | video in  Google drive - folder "Infinite Recharge at Home/Video for submission"
HyperDrive Slalom |  08.97s | 0 | video in  Google drive - folder "Infinite Recharge at Home/Video for submission"

**Comment by jhajel** [comment]
I counted up the PowerPort challenge from the video mah00101 and it came to 4 perfect cycles for a total of 36 points.  We need to get to 5 cycles.  There was about 6-8 seconds of lining up for each of the cycles (after the first) that we could get some time back.  Let's try to get to 5 cycles on Wednesday.

**Comment by jhajel** [comment]
The accuracy challenge only has 14 points instead of the max 18.  We missed 2 shots - 1 in the first cycle and 1 in the 2nd.  If you have time, please re-record this one.  Also, make sure that we load the power cells only in the re-introduction zone.  This is not high priority, but right now there aren't many scores in that challenge for our group.

**Comment by alevin** [comment]
Skills Challenge | time | penalty (markers hit) |Notes
-----|-----|-----|-----
HyperDrive Lightspeed |  20.16s | 0 | video in  Google drive - folder "Infinite Recharge at Home/Video for submission" , [video](https://photos.app.goo.gl/rWxcRqu5v8Ypnss47)

**Comment by jhajel** [comment]
Fantastic time!  I am going to start to upload AutoNav and Galactic Search videos now.  I don't think we will change those before tomorrow.  Do you we expect to have different HyperDrive videos?

**Comment by jhajel** [comment]
I uploaded the Interstellar Accuracy challenge with a score of 18 to the FRC site.  When you upload the Power Port video, I will do that.  I plan to final submit at 10am tomorrow.

**Comment by jhajel** [comment]
54 for Power Port!  Well done!

**Comment by jhajel** [comment]
This Accuracy video has the LightSpeed graphic.  I don't think we need to change it.  I can also upload the one without the timer.

https://drive.google.com/file/d/10lFV7Hq1lfzK8GX87oCSAEMDwAb1xYrc/view?usp=sharing

**Comment by jhajel** [comment]
Ok, on the scores for our group, the top Hyperdrive is 48.9 and our time is 50.6  And chance you can find time to shave 1.7 seconds off one of our hyperdrives before 11:30?

**Comment by alevin** [comment]
I'll review the videos, do you know which one  has the most potential to shift start/finish time ?

**Comment by jhajel** [comment]
My guess would be the barrel run.  We need to submit the video by 11:30am because we may risk not getting it in.

**Comment by alevin** [comment]
looking at ... 
found that bounce video contains incorrect time in the text ( 12.02 ) filename and timer were correct
uploaded corrected video to Gdrive folder - HyperDrive_Bounce_Apr4_11.02s_fixedtext.mp4

**Comment by jhajel** [comment]
But there is a HyperDrive Bounce that is 10.21.  Should I not use that one?

**Comment by jhajel** [comment]
This is what I have so far.  Please double check that this is correct.

https://docs.google.com/spreadsheets/d/1hon5MRLS47aLoeBlcUAX2H4hQqfORnTm2V3UvvDnpOE/edit#gid=0

**Comment by alevin** [comment]
on "10.21" bounce one finish cone was not placed correctly - not sure if it is critical or not
reviewing if we've got better barrel runs

**Comment by alevin** [comment]
uploading barrel with time 11:03, checking if there are any better results

**Comment by jhajel** [comment]
I can't see the difference on the 10.21 bounce cone placement.  Would the misplaced code affect our time?  If not, I am going with 10.21.

**Comment by alevin** [comment]
![Screenshot from 2021-04-08 11-05-10](https://user-images.githubusercontent.com/1231948/114075415-5f670e00-985a-11eb-9eca-cb927e3e56c2.png)

**Comment by jhajel** [comment]
I see.  I will upload the 11.02 one.

**Comment by alevin** [comment]
11:03 barrel run was the best for the day

**Comment by jhajel** [comment]
Ok, anything else coming?  We have 18 minutes.  I will submit and lock at 11:50.

**Comment by jhajel** [comment]
Submitted!
