### ISSUE TITLE
optimize bounce run

### ISSUE THREAD

**Issue by alevin** [gwhs/FalconRecharged2021#12]
[video from the run](https://photos.app.goo.gl/JocbBR1oLzpU6ao79)

path:

```java
   public static double[][] bounce = {
        { 30, 90 },
        { 85, 90 },
        { 90, 45 },
        { 120, 140 },
        { 170, 140 },
        { 180, 45 },
        { 190, 130 },
        { 250, 130 },
        { 260, 40 },
        { 270, 85 },
        { 330, 85 },
       };

```
![image](https://user-images.githubusercontent.com/1231948/110214512-c3607600-7e59-11eb-9874-32a1ba79ece0.png)

**Comment by jhajel** [comment]
Ok, that's really awesome.  Well done!

**Comment by alevin** [comment]
@leinouye ,  this site [Gnuplot instantly](http://gnuplot.respawned.com/) can help to visualize points on the map.
use is simple - for the current point in bounce run add to "data" block:

```csv
30,90
80,80
95,30
100,90
135,145
175,135
190,30
190,130
255,130
275,30
270,85
330,85
```

and plot script can be:

```
# Scale font and line width (dpi) by changing the size! It will always display stretched.
set terminal svg size 400,300 enhanced fname 'arial'  fsize 10 butt solid
set output 'out.svg'
set size ratio -1

set datafile separator ","
set xrange [0:360]
set yrange [-180:0]
set xtics 30
set ytics 30
set grid back

set style line 1 \
    linecolor rgb 'blue' \
    linetype 1 linewidth 1 \
    pointtype 2 pointsize 1.5

set style line 2 lc rgb 'red' pt 9 pointsize 2  

plot 'data.txt' using 1:($2*-1):($0+1) with labels notitle , \
     '' using 1:($2*-1) with lines linestyle 1 notitle
```
and you'll get result as:

![image](https://user-images.githubusercontent.com/1231948/111251417-8f1d5000-85e5-11eb-8338-70e82caebe46.png)


add/remove/change points in the "data"  to see the change in the trajectory.

**Comment by alevin** [comment]
@leinouye , @anton-levin , nice job on bounce  ( 1836cd0  ,  tagged as "Bounce_0.1" ) !

[latest video](https://photos.app.goo.gl/T7gS2FKaKhVhpCwYA)

**Comment by alevin** [comment]
Bounce - nice and clean - 19.7 sec 
great job , @leinouye , @anton-levin , @zhxu033 !
[Bounce run vidoe](https://photos.app.goo.gl/Gu2JtScnMmsNc1xw6)  

trajectory map  ( from [FalconRecharged2021_trajectories/python](https://github.com/gwhs/FalconRecharged2021_trajectories/tree/main/python/alternative_bounce) ):
![trajectory](https://github.com/gwhs/FalconRecharged2021_trajectories/raw/main/python/alternative_bounce/bouncefix1.png)

git commit  - 762f7cc

**Comment by alevin** [comment]
Closing the issue , we've got successful run which should be acceptable for submission.
we'll re-open  ( or open new case ) if we'll have time to improve after completion of other challenges.

great  job , @anton-levin ,  @leinouye , @zhxu033  !
