### ISSUE TITLE
Add a parameter for the RPM to the Autoshoot constructor

### ISSUE THREAD

**Issue by jhajel** [gwhs/FalconRecharged2021#13]
This may be useful for the Accuracy Challenge.  Will assign Leanna once we get her in the organization.

**Comment by leinouye** [comment]
added another constructor

**Comment by jhajel** [comment]
Need help pushing changes to Main branch.

**Comment by alevin** [comment]
@jhajel , try to pull and changes done by @zhxu033  
``` 
git pull --rebase 
```
and commit/push after

**Comment by jhajel** [comment]
I think we got this working.  Closing.
