### ISSUE TITLE
BOM for Robot Running

### ISSUE THREAD

**Issue by anton-levin** [gwhs/FalconRecharged2021#16]
Here's a list of stuff we need to keep robot driving.
1. [VersaWheel](https://www.wcproducts.com/217-3197) - count: 4
the original swervedrive wheels, we want to compare them to hi grip see performance differences. We can also use these to pull better dimensions for the hi grip wheels.
2. [HiGrip Wheels](https://www.andymark.com/products/higrip-wheels-options?via=Z2lkOi8vYW5keW1hcmsvV29ya2FyZWE6Ok5hdmlnYXRpb246OlNlYXJjaFJlc3VsdHMvJTdCJTIyYnV0dG9uJTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIycSUyMiUzQSUyMmFtLTIyNTYlMjIlMkMlMjJ1dGY4JTIyJTNBJTIyJUUyJTlDJTkzJTIyJTdE&Diameter=4%20in.&quantity=1&Durometer=80A) - count: 6
We have two fresh ones already, and 6 more will continue operations. These are used to keep the robot running for autonomous and when the rims are out of rubber.
3.  [Neoprene Rubber Strip](https://www.mcmaster.com/1372N17-1372N175/) - count: 2
This is rubber for the rims, we have enough to swap 2 wheels, getting 2 more strips lets us have 2 all-wheel swaps.
4. [Ultra-Strength Neoprene Rubber](https://www.mcmaster.com/1310N75-1310N753/)  - count: 2
This stuff is a lot more durable and has less of a chance of crumbling. This rubber is stronger, but likely even more stiffer. Something to note is that they are 2in wide, but I found a couple of techniques for smoothly cutting rubber.
5. [Rivets](https://www.amazon.com/gp/product/B07QJWSKRD/ref=ox_sc_act_title_2?smid=A2I6Z759BTJP4J&psc=1) - count: 5
All the rivets, all of which are needed for swaps, with about a dozen to spare.
6. [Cones](https://www.amazon.com/Franklin-Sports-Flexible-Soccer-Cones/dp/B003KV79RS/ref=sr_1_20?dchild=1&keywords=cones%2Bspringy&qid=1615250843&sr=8-20&th=1) - count: 5
Better than water bottles filled with water that are very easy to burst, and are half off (aka a steal!)

**Comment by jhajel** [comment]
I'll make the order and post the tracking numbers.

**Comment by jhajel** [comment]
Would this work for the rivets?  Can you find them on McMaster?  https://www.mcmaster.com/97447A145/

**Comment by jhajel** [comment]
Made the order.  Everything but the hi-grip wheels should come 3/10 or 3/11.

**Comment by anton-levin** [comment]
Hajel, I accidentally forgot one more item:
7. [Back-Up Washers #1](https://www.mcmaster.com/90183A213/) - count: 1 or [Back-Up Washers #2](https://www.amazon.com/Magery-Aluminum-Backup-Washers-Diameter/dp/B0897142XZ/ref=sr_1_2?dchild=1&keywords=1%2F8+aluminum+backup+washers&qid=1615336438&sr=8-2) - count: 1
Backup washers go behind the rivets to make sure that rivets stay in place. I recommend the Amazon one because the McMaster pack will have 500, and the Amazon one will come in quicker.

**Comment by jhajel** [comment]
> Hajel, I accidentally forgot one more item:
> 7. [Back-Up Washers #1](https://www.mcmaster.com/90183A213/) - count: 1 or [Back-Up Washers #2](https://www.amazon.com/Magery-Aluminum-Backup-Washers-Diameter/dp/B0897142XZ/ref=sr_1_2?dchild=1&keywords=1%2F8+aluminum+backup+washers&qid=1615336438&sr=8-2) - count: 1
> Backup washers go behind the rivets to make sure that rivets stay in place. I recommend the Amazon one because the McMaster pack will have 500, and the Amazon one will come in quicker.

Ordered from Amazon.  Coming tomorrow.  The wheels from Andymark should come Monday.  Closing issue for now.  Re-open if you need anything else.  No shipping date on the wheels from WCP but I would expect them to come tomorrow.  Keep an eye out for packages.
