### ISSUE TITLE
Autonomous Fidget

### ISSUE THREAD

**Issue by anton-levin** [gwhs/FalconRecharged2021#19]
At the start of autonomous for autoNav and galactic search, the swerve drives do a weird fidget thing where the turning motors spin the swerve drives around. Usually throws off the robot x/y placement and rotation by a little bit.

**Comment by jhajel** [comment]
Is it all the wheels?  Note the position of the bevel gear with each of the wheels and then spin the wheel manually 180 degrees and restart the auton and see if it does it again.
