### ISSUE TITLE
Spring Break Meetings

### ISSUE THREAD

**Issue by anton-levin** [gwhs/FalconRecharged2021#23]
Tomorrow we are meeting between 1:00 PM to 5:00 PM PT (4:00 PM to 8:00 PM ET)
In this room: [Zoom](https://sfusd.zoom.us/j/3161508049?pwd=SGlxVzRwOHJqZmtBTlcrQ3hLYTA2QT09)

For the rest of the week, please fill out your availability [here](https://www.when2meet.com/?11470163-mALb3). (you can also change the time zone top left to skip maths)
We'll try meeting all week, if we get stuff done pretty quick and early then we can skip extra meetings.

**Comment by RobertTheBlair** [comment]
I can do quick checkins for advice if needed, but work is continual

**Comment by jhajel** [comment]
I will check in again today.  You guys are making good progress.  Let's meet our normal time on Saturday 10-2.
