### ISSUE TITLE
Power Port Challenge Flow

### ISSUE THREAD

**Issue by jhajel** [gwhs/FalconRecharged2021#27]
1. Pre-load robot with 3 power cells (non-damaged) at the base of the scoring wall
2. Start timer
3. Shoot 3
4. 2 human players catch 3 power cells, run back to re-introduction zone
5. drive robot back to re-introduction zone
6. human players load 3 same power cells
7. drive back to scoring wall - better to run into it.
8. Repeat steps 3-7 as many times in 60s

Notes:

- You must use the same 3 power cells for the entire 60s.
- Human players cannot touch the robot while loading
- It would be nice if the robot could run into the base of the portal for faster alignment
- Driver should sit directly behind the re-introduction zone, lined up with portal for faster alignment
- Will need a button to start the flywheel as you drive to the wall
- May need to add inertial flywheels to increase accuracy of 2nd and 3 shot.
- Human players do not need to be students, but the driver does
- Power cells released within the 60s but not yet in contact with the portal still will count
- 5-7 cycles should be what we go for.
- It may be faster to load directly to conveyor rather than use the in-take.  This should be tested.

**Comment by jhajel** [comment]
Here is the video of a team doing 9 cycles.  I don't think we can do that, but you can see how much work it is for the human players.

https://www.youtube.com/watch?v=W0cnASb7tb8

**Comment by alevin** [comment]
videos are uploaded to the same [album](https://photos.app.goo.gl/GXKwWM4igZ7KB699A) 
only last one was counted - score 35 ( unless I've miscalculated ) 
looks like it was the best for the day.
