### ISSUE TITLE
The Shooter Shooting Backwards

### ISSUE THREAD

**Issue by letawara** [gwhs/FalconRecharged2021#5]
When I press the left bumper, the shooter revs up but spins the wrong way. Please fix I do not want the power cells going in the robot.

**Comment by jhajel** [comment]
We should use the AutoShoot command for shooting.  It revs up, backs up the conveyor and thens hoots.

**Comment by RobertTheBlair** [comment]
see the command `SetShooterSpeed` - the constructor has a parameter `rpm`

**Comment by jhajel** [comment]
start.whenPressed(new AutoShoot(conveyorT, shooterMotor,false)

This is the autoshoot.  The boolean at the end determines if the conveyor will backup before revving up the shooter.  Use true when picking up for the PowerPort Challenge.  I think it should be false for the Accuracy Challenge, but this can be tested.

**Comment by zhxu033** [comment]
fixed in the main branch

**Comment by RobertTheBlair** [comment]
basic issue fixed
