### ISSUE TITLE
Annoying Issue - robot drift

### ISSUE THREAD

**Issue by anton-levin** [gwhs/FalconRecharged2021#6]
When given input to move directly forward, the robot seems to rotate about its center. It keeps field orientation, and the movement id reversible (exaggerated example : if the robot moves forward 10m and turns 90 degrees, I can make it go back 10m and its rotation will be in the same position) Reality is that its about 1 degree per 45in

**Comment by jhajel** [comment]
Are you still seeing this?

**Comment by anton-levin** [comment]
Yes definitely, pretty significant after runs like slalom.
