### ISSUE TITLE
Need a nice photo of intake

### ISSUE THREAD

**Issue by jhajel** [gwhs/FalconRecharged2021#7]
Can we get a landscape photo of the robot from the front about to intake a PC with 2 power cells already in conveyor.  Please take a couple from different horizontal and vertical angles.

**Comment by alevin** [comment]
![20210227_144831](https://user-images.githubusercontent.com/1231948/109426631-813fbc00-79a3-11eb-81e8-1543552a8247.jpg)
![20210227_145143](https://user-images.githubusercontent.com/1231948/109426634-8270e900-79a3-11eb-9069-0b9aa029b810.jpg)
![20210227_145211](https://user-images.githubusercontent.com/1231948/109426636-83a21600-79a3-11eb-9400-36307ec5ca04.jpg)
![20210227_145220](https://user-images.githubusercontent.com/1231948/109426637-84d34300-79a3-11eb-9fbc-6cf08a3c2acd.jpg)
![20210227_145331](https://user-images.githubusercontent.com/1231948/109426639-869d0680-79a3-11eb-9d8c-ad8968eb675f.jpg)
![20210227_145440](https://user-images.githubusercontent.com/1231948/109426645-87ce3380-79a3-11eb-8f6b-7ec8757eb086.jpg)
![20210227_145444](https://user-images.githubusercontent.com/1231948/109426648-8997f700-79a3-11eb-8405-30d3f86444f8.jpg)

**Comment by jhajel** [comment]
Thanks, these are perfect.  Closing the issue.

**Comment by jhajel** [comment]
Leah, can you add the best picture to that one collage picture?  Thanks.

**Comment by jhajel** [comment]
Great job.  Thanks!
