### ISSUE TITLE
improve slalom path

### ISSUE THREAD

**Issue by alevin** [gwhs/FalconRecharged2021#9]
Slalom run from 03.01  is a good starting point  ( ~12 sec, one marker touched ) 

 [Code](https://github.com/gwhs/FalconRecharged2021/releases/tag/Ver.2021.03.01)

video of the run is at [Video](https://photos.app.goo.gl/FBsUHLiqdSGgeb2B9)

Trajectory  (src/main/java/frc/robot/TrajectoryHelper.java) 

```java
    public static double[][] slalom = { 
        {30,150},
        {80,145},
        {95,90},
        {235,90},
        {250,145},
        {300,145},
        {300,90},
        {250,90},
        {230,145},
        {95,145},
        {60,90},
        {30,90},
               };
``` 
![image](https://user-images.githubusercontent.com/1231948/109730520-76855280-7b6e-11eb-8f2a-7f1d654d57c8.png)

Compare actual run with trajectory and  optimize the path.

**Comment by jhajel** [comment]
Can this issue be closed?  Are we optimizing this any more?

**Comment by alevin** [comment]
Closing the issue , we've got successful run which should be acceptable for submission.
we'll re-open  ( or open new case ) if we'll have time to improve after completion of other challenges.

great  job , @anton-levin ,  @leinouye , @zhxu033  !
